### ISSUE TITLE
При отмене закладки ставиться лайк, и на оборот

### ISSUE THREAD

**Issue by Be11ator** [yorkblansh/blago-fonds-panel#4]
Если лайк не постановлен а фонд добавлен в закладку, при отмене закладки ставится лайк. Также иногда, когда пользователь ставит лайк фонд тоже добавляется в избранное 
![image](https://user-images.githubusercontent.com/85112393/171386281-899f8f08-258b-4270-8bc4-6a5642860b48.png)

**Comment by yorkblansh** [comment]
баг исправлен
